# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a0c3153bbdb214e0618589ba9b01a23dc596ca77ce4adb7dc255414d74e54cfc94adc1bcaba9034cf2b0cb88f6166a2322a512e81d79486538fd8e26f4a7de7

test:
  secret_key_base: c5114b651c9f03a50c36a44263919341d2086e91b46f99e52a2f11c3de5076ed7b9e7ab45143a54de14f279beb99ddfd07d61c49ff8b5806b6fdf5dfaeeaa995

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
